# =============================================================================
# joint_limits.yaml — Kerabot MoveIt2 Joint Limits
# =============================================================================

default_velocity_scaling_factor: 0.5
default_acceleration_scaling_factor: 0.5

joint_limits:
  Revolute_1:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_jerk_limits: true
    max_jerk: 50.0

  Revolute_2:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_jerk_limits: true
    max_jerk: 50.0

  Revolute_3:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_jerk_limits: true
    max_jerk: 50.0

  Revolute_4:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_jerk_limits: true
    max_jerk: 50.0

  Revolute_5:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_jerk_limits: true
    max_jerk: 50.0

  ee_rotation_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_jerk_limits: true
    max_jerk: 50.0
