# =============================================================================
# pilz_industrial_motion_planner_planning.yaml — Pilz Pipeline Configuration
# =============================================================================

planning_plugin: pilz_industrial_motion_planner/CommandPlanner
default_planner_config: PTP
request_adapters: ""

capabilities: >-
    pilz_industrial_motion_planner/MoveGroupSequenceAction
    pilz_industrial_motion_planner/MoveGroupSequenceService
